version: 0.0
os: linux
files:
  - source: build/
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  ApplicationState:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root